### ISSUE TITLE
cast member function mangled

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#1007]
Loses space before global scope operator, adds spaces around
ampersand and in parens. Not consistent with regular member
functions

```
	operator const ::foo::Bar&() const
	{
		return bar;
	}
```

See operator.cpp, operator.cpp.uncrustify, operator.debug in https://github.com/jlee975/uncrustify-tests

Using uncrustify v0.64_d 1f538888ad9b3adc8a46828ebe2ad6578629df29

**Comment by CDanU** [comment]
This boils down to:

C:
```sql
sp_arith                        = force
sp_inside_paren                 = force
sp_before_dc                    = remove
```
I:
```cpp
operator const ::foo::Bar&() const
{
		return bar;
}
```
O:
```
operator const::foo::Bar&( ) const
{
	return bar;
}
```

**Comment by jlee975** [comment]
I think I submitted a patch awhile back to not apply sp_before_dc to global scope operators (a "leading" double colon). It worked for what I tested, but I might have missed something (being not-very-familiar with the code).

**Comment by guy-maurel** [comment]
May we close the call.

**Comment by jlee975** [comment]
While the issue has been identified, I feel it still needs a fix. A slightly longer example may clarify the issue. The styling of "::foo::Bar&" is different in the following cases:

I:
```
class T
{
public:
	const ::foo::Bar& get() const
	{
		return bar;
	}
	operator const ::foo::Bar&() const
	{
		return bar;
	}
private:
	foo::Bar bar;
};
```

O:
```
class T
{
public:
	const ::foo::Bar& get() const
	{
		return bar;
	}

	operator const::foo::Bar & ( ) const
	{
		return bar;
	}
private:
	foo::Bar bar;
};
```

It seems in the case of the operator, it is being parsed as an arithmentic expression, when it is really a reference to a type.

I expect sp_inside_fparens, sp_before_byref, sp_after_byref, to apply.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
And report.

**Comment by jlee975** [comment]
I cloned today, rebuilt and reran, but no change in the output. The debug file changed, so I've uploaded that to the uncrustify-tests repo.

**Comment by guy-maurel** [comment]
Which branch are you using?
Which Platform, compiler?

**Comment by jlee975** [comment]
Pulled two days ago. Commit was 89fdcefb2eb33b114c3de1edc3ed072f0b090e13 on master.

On Centos 7.3. Using gcc version 4.8.5.

**Comment by CDanU** [comment]
I also still see that the ref is influenced by `sp_arith` and that `sp_inside_paren` adds a space between the empty paren pair even if `sp_inside_fparen = remove`.
`sp_before_dc` should be fixed once #1063 is merged

**Comment by gmaurel** [comment]
Bug is fixed. Please test it.

**Comment by CDanU** [comment]
Unfortunately I still get:
```
operator const::foo::Bar & ( ) const
```
in the output.

**Comment by jlee975** [comment]
It is a cast operator (to a const reference to foo::Bar). It is written as

```
operator type() const
```

**Comment by jlee975** [comment]
Can confirm that bug is still present as of a6b9710b91e47e795947b1db0293ebe7c1fe655d, pulled this morning.
