### ISSUE TITLE
Fixes that are needed to build on windows.

### ISSUE THREAD

**Issue by meldavis** [uncrustify/uncrustify#470]
In file: "compat_win32.cpp", need to change `text()` back to `str.c_str()`. (Refer to https://github.com/uncrustify/uncrustify/commit/9a8ad0599e4bfa7310ce4b7d9169b9c099f052a6). It breaks building on windows. This particular usage of `c_str()` is not related to parsing or chunking text.

If the VisualC solution is being maintained, need to add  "options_for_QT.cpp" and "options_for_QT.h" to the project file.

With these changes, it builds with MSVS 2015.

**Comment by gmaurel** [comment]
Done for "text()"
Which "project file" do you mean?

**Comment by dirk-thomas** [comment]
He is referring to https://github.com/uncrustify/uncrustify/blob/44ce0f156396b79ddf3ed9242023a14e9665b76f/win32/Uncrustify_Win32_2011.vcxproj#L132-L192 as well as the sibling files for different versions.

**Comment by jibsen** [comment]
You also need the generated files `uncrustify_version.h` and `token_names.h`.

**Comment by dirk-thomas** [comment]
The script `create_uncrustify_version_header.bat` can be used to generate `uncrustify_version.h` but it needs to be patched: https://github.com/ament/uncrustify/commit/14ef205df4e956a383169feade52db88e26a832f#diff-893df67e276f4269bc389cf0e317ebdc

And it would be nice to include VS 2015 project files (once Windows builds again). We have created them in our fork (converted from the previous VS version and updated to build 0.62): https://github.com/ament/uncrustify/tree/master/win32

**Comment by dirk-thomas** [comment]
The new version also introduces seven compiler warnings on Windows:

* combine.cpp:283: 'UINT64': forcing value to bool 'true' or 'false' (performance warning)
* combine.cpp:1273: 'int': forcing value to bool 'true' or 'false' (performance warning)
* indent.cpp:1010: 'UINT64': forcing value to bool 'true' or 'false' (performance warning)
* keywords.cpp:380: 'int': forcing value to bool 'true' or 'false' (performance warning)
* output.cpp:397: 'UINT64': forcing value to bool 'true' or 'false' (performance warning)
* tokenize.cpp:299: 'int': forcing value to bool 'true' or 'false' (performance warning)
* tokenize.cpp:300: 'int': forcing value to bool 'true' or 'false' (performance warning)

**Comment by dirk-thomas** [comment]
It looks like the Windows regressions are more severe. The following files in our code were fine with uncrustify 0.62 but version 0.63 simply segfaults on Windows trying to parse them:

* https://github.com/ros2/rclcpp/blob/0a9f2e26a217e10cd236cfc6c33f51cb6adb58d0/rclcpp/include/rclcpp/node_impl.hpp
* https://github.com/ros2/rclcpp/blob/0a9f2e26a217e10cd236cfc6c33f51cb6adb58d0/rclcpp/include/rclcpp/publisher.hpp
* https://github.com/ros2/rclcpp/blob/0a9f2e26a217e10cd236cfc6c33f51cb6adb58d0/rclcpp/include/rclcpp/subscription.hpp

Also in another case the parser failed on a file (on all platforms) which I was only able to pass by changing the source files (again the same file worked with 0.62): https://github.com/ros2/rmw_connext/commit/f1a87c2c1c73796e83eec0e3a84158944ceefdcb

**Comment by gmaurel** [comment]
This is a problem which was not raised before.
The run produces an error: "the stack depth is too small" I have to look for why.
Thanks for the comment.

**Comment by dirk-thomas** [comment]
Since a lot of independent issues are mentioned in this ticket I will try to enumerate them (in the order they should be resolved in):

* build on Windows
  * [ ] update Visual Studio project files with new source files
  * [ ] patch `create_uncrustify_version_header.bat`
  * [ ] convert `make_token_names.sh` into a cross-platform Python script
  * [ ] `compat_win32.cpp` needs to change `text()` back to `str.c_str()` (I didn't run into this problem though)
  * [ ] provide a way to run the tests (something like `run_tests.sh` for Windows)
    * this would be immediately possible if CMake would be used
* address regressions
  * [ ] new segfaults when parsing some files
  * [ ] unmatched brackets / braces / etc. when parsing some files

After that the following things are nice to haves:
* [ ] setup automated testing for all platforms
* [ ] Add Visual Studio 2015 solution and project file
  * IMO replacing `autotools` with CMake would get rid of manually maintaining Visual Studio files
* [ ] Address compiler warnings

Please let me know what you think. I am happy to help but would like to avoid redundant work or creating patches which won't be accepted.

**Comment by dirk-thomas** [comment]
I have updated my previous comment to reference the new PRs #482, #483, #484 and #485 which together allowed me to build on Windows again and run the tests. Several of them fail atm.

**Comment by jibsen** [comment]
I took a stab at making a CMake script for uncrustify:

https://github.com/jibsen/uncrustify/tree/use-cmake

The script generates `uncrustify_version.h` and `token_names.h` and includes the win32 folder when compiling on Windows. I also attempted to generate a usable `config.h` on non-Windows systems.

I don't know, perhaps it could serve as a starting point if the authors wish to try using CMake?

**Comment by gmaurel** [comment]
I am missing a src/CMakeLists.txt which should generate src/config2.h.in

**Comment by jibsen** [comment]
The extra `config2.h.in` was mostly a hack to see if it were possible to have CMake generate the `config.h` file. I updated the branch with a CMake script that generates its own `config.h.in` and uses that. It seems to work on Windows (mingw-w64, VS 2015) and Linux here.

If you are interested in using any of this, I am happy to open a PR to discuss. I think the testing would require a change to the test runner so it can take the path to the uncrustify executable as an argument.

With this you could also potentially set up an AppVeyor CI to test building with VS.

**Comment by gmaurel** [comment]
Yes, I wish that. It would be fine.
I havn't enought experience with cmake nor with Windows.

**Comment by jibsen** [comment]
I am pretty new to CMake myself, but I got to play around with it while helping out getting squash to compile on Windows.

I am seeing some segfaults similar to @dirk-thomas, it's due to using `ent` in width.cpp:310 even if no solution was found (`ent` is still zeroed).

**Comment by gmaurel** [comment]
This is solved:
 if we don't get a solution at split_line:
  "TRY_SPLIT yielded NO SOLUTION"
 we must return
look at git 562eb38bd3c13934a52d9491145ace0985ac96cc
Please send next time an example source.

**Comment by jibsen** [comment]
Sorry, it was the unit tests that crashed, specifically 00901, 00902, and 00903. With the fix they run now.

**Comment by gmaurel** [comment]
Yes, I know.
It is now corrected.

**Comment by dirk-thomas** [comment]
What about my pull requests on this? Can they be reviewed / merged?

**Comment by gmaurel** [comment]
Fine, but I need some more time to test. Thanks

**Comment by jibsen** [comment]
@dirk-thomas thanks for maintaining the list. I believe 562eb38 along with #495 and the gitattributes file should make the unit tests pass on Windows now. You may need to pick up #494 to run them with CTest, and you will have to refresh any checked out files to pick up the line ending changes.

The test files you linked earlier do not appear to crash anymore either.

**Comment by dirk-thomas** [comment]
I have tried the current master (using CMake) with the following result:

* on Windows uncrustify doesn't segfault anymore for my use cases :tada:
* I tried to address the compiler warnings without changing the current semantic of the code, see #499
* it is still unable to parse previously working sources e.g. this change is necessary but ugly and shouldn't be necessary: https://github.com/ros2/rmw_connext/pull/161/commits/f1a87c2c1c73796e83eec0e3a84158944ceefdcb
* it still forces changes to comply even if the same source passed with older uncrustify versions: e.g. https://github.com/ros2/rclpy/pull/26/commits/ace201205f9477f9fbb5a21733cd1de804c3fbf4

Since these style changes are not following our configuration and have worked in the previous version of uncrustify can they be considered as regressions and be fixed?

**Comment by dirk-thomas** [comment]
Sorry, for not commenting earlier. I didn't find time for code style stuff again until now. I just tried the latest master which addresses #509 as well as #524. With those being fixed (and using the new CMake-based build) it works fine for me on Windows again (almost all existing code passes, as it did with earlier versions, I will fill a separate ticket for the case which doesn't). Thank you!

I updated the bullets in the earlier comment. One remark regarding `compat_win32.cpp` is pending but there was no feedback from the user who raised it. Other then that the only pending checkboxes are for the tests / automating the tests on Windows. I created a separate issue for this: #538

I think this ticket can be closed.

**Comment by dirk-thomas** [comment]
I haven't looked into any of the tests but the build on our fork ha several of them failing on Windows: http://ci.ros2.org/job/ci_windows/1571/testReport/junit/projectroot/tests/test_uncrustify/

Therefore I think #538 is urgently necessary since it seems to be not tested by the developers atm.

**Comment by mihaipopescu** [comment]
I think we should have one cross platform build system. If CMake was chosen then try replacing GNU autotools scripts with CMake as well and then we can remove all IDE project files. What you think about  this ?

**Comment by dirk-thomas** [comment]
Absolutely, the instructions should mention CMake and then all other Make / Visual Studio files should be removed.

I made that comment on the CMake ticket: https://github.com/uncrustify/uncrustify/pull/492#issuecomment-223014326

**Comment by todd-richmond** [comment]
IDE project files are helpful for anyone using the IDE to debug. Should be able to eliminate all but the latest rev IDE file though

**Comment by dirk-thomas** [comment]
You should generate the Visual Studio project files using CMake. No need to keep them in the repo.

**Comment by gmaurel** [comment]
Still any comment?
Can we close the call?

**Comment by mihaipopescu** [comment]
I think you can close it.
