### ISSUE TITLE
indent_continue is sometimes disobeyed

### ISSUE THREAD

**Issue by BugZappr** [uncrustify/uncrustify#478]
I had the code:

    QString fileName = QFileDialog::getOpenFileName(this,
      tr("Choose Configuration File"), ui->leStrategyFile->text(),
      tr("Configuration Files (*.cfg);; All Files (*.*)"), 0);

and told uncrustify to reformat the method it contained.  When I have "indent_columns=4" and "indent_continue=2", I get:

    QString fileName = QFileDialog::getOpenFileName(this,
        tr("Choose Configuration File"), ui->leStrategyFile->text(),
        tr("Configuration Files (*.cfg);; All Files (*.*)"), 0);

Since my Indent Continue is 2, the continuation lines should not be indented by four, but by two spaces.:

Note that the following example code correctly retains its formatting:

    if (strcmp("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))
        b=1;

This second example misbehaved in version 0.59, but with six instead of four spaces of indentation in the continuation line,  It does now work correctly in the current version.

I don't understand why the QString example doesn't indent right, but the "if" now does.  Other continuation lines correctly indent two spaces.  Trying it in UniversalIndentGUI, as suggested, but dropping in the latest version of Uncrustify, I tried toggling all the other indent options.  None of them seemed to solve the problem.  If there is some special attribute about the first example that causes it to be indented differently, and that is by intent, you might create a new setting to handle continuation lines in this special case.  I also note that some people like to indent their continuation lines of their "if" statements six spaces.  To that end, I also propose you create a new continuation indent setting to override it, e.g.: "conditional_indent_continue=6". 

My current config is attached, where the .cfg extension has been changed to a .txt.

[uncrustify.txt](https://github.com/uncrustify/uncrustify/files/253899/uncrustify.txt)

My current version is uncrustify 0.62.0-g5987f22.

**Comment by gmaurel** [comment]
Use the new option:
  use_indent_continue_only_once=true

**Comment by BugZappr** [comment]
The name of the option seems to describe something different than what I'm getting.  It seems to be misnamed.

I would expect it to produce, say:

```
  QString fileName = QFileDialog::getOpenFileName(this,
    tr("Choose Configuration File"), ui->leStrategyFile->text(),
      tr("Configuration Files (*.cfg);; All Files (*.*)"), 0);

```
That being said, it fixes my unintuitive problem.  It seems to me that the default options still fail to observe the continuation indentation.  While it seems like  a kludge, I'd prefer to have a kludge available than none at all.

**Comment by BugZappr** [comment]
Here's another case where the indent_continue fails to be heeded:

    pSettings = new QSettings(QCoreApplication::applicationDirPath() + "/" +
        QCoreApplication::applicationName() + ".ini",
      QSettings::IniFormat);

This, even with the new option.

**Comment by BugZappr** [comment]
It don't know if it fixed my prob or not.  I'm getting Unknown symbol 'use_indent_continue_only_once'.  I fixed the indentation, and ran it from within Qt Creator.  When it didn't change, I assumed it had been reformatted, and was fixed.

**Comment by gmaurel** [comment]
The issue is similar to bug #651

There is one option to make indentation for the continuation line:
  indent_continue

The value of the indentation for a continuation line is calculate
differently if the line is:
  a declaration :your case with QString fileName ...
  an assigment  :your case with pSettings = new QSettings( ...

At the second case the option value is use twice:
  at the assigment
  at the function call

If you want to prevent the double use of the option value
you may use the new option :
  use_indent_continue_only_once

with the value "true".

To remain compatible with old version of uncrustify, the default
value is set to "false".

**Comment by BugZappr** [comment]
I believe you are saying that you have a new option that allows the indent continue setting to be used as an indentation for all the second and later lines of any multi-line statement.  However, "use_indent_continue_only_once" is not working in the latest Uncrustify.  Also, it is confusing terminology IMHO; in that might not be very intuitive that it is not referring to using indent continue on just a single line, (a single instance?) but is referring to using only a single value for indent continue.  I would suggest the somewhat less ambiguous: "single_indent_continue_value".  If this is not true, but in the default behavior, with declarations continues one way and assignments another, then it only seems fully customizable that these be separate settings as well, such as "assignment_indent_continue", "declaration_indent_continue" and perhaps "assignment_declaration_continues_add".  As things stand before the availability of single_indent_continue_value, I don't see where the rules are actually spelt out anywhere, or that they are fully customizable (as one might hope).

If the option is coming in a future version, then I will be happy for that, whatever it is named.  It is presumably in your working copy; that evidently hasn't made it to release yet.  In any event, I'll be looking forward to it.

**Comment by gmaurel** [comment]
Hello BugZappr!
I fixed the issue yesterday, uploaded the corrected source. Today a bigger explanation to this option.
Please use the git source to test it. Thanks for the comment.

**Comment by BugZappr** [comment]
I'm not having a lot of luck building it from the .SLN in Windows.

**Comment by BugZappr** [comment]
Heh.  Guess I was supposed to post this at SourceForge instead.  Sorry.  Thx for prompt responses; and an extremely promising code formatter.  Google ppl think reformatting code is a major waste of programmers' time - which interested me.  I can integrate uncrustify in Qt creator as an external tool without too much trouble.  Will look forward to testing with these examples next time you drop a release.

**Comment by BugZappr** [comment]
OK.  I tried uncrustify 0.63 just now.  Sorry it took me so long to notice that there was a new version.  It no longer crashes on seeing the option use_indent_continue_only_once; and it works on the example correctly.  However, if I take out the type identifier "QString" from the example, both lines are indented at four instead of two spaces - in spite of my "indent_continue=2".  I might have opened a separate issue on this, given that you fixed the example on this issue, but it still falls more broadly under being able to set it to always respect indent_continue in function bodies.

For the sake of clarity, the following code is indented with four spaces of continuation as follows, but should have two:

    fileName = QFileDialog::getOpenFileName(this,
        tr("Choose Configuration File"), ui->leStrategyFile->text(),
        tr("Configuration Files (*.cfg);; All Files (*.*)"), 0);

**Comment by BugZappr** [comment]
I see where this very getOpenFileName statement has been added to the test data, which gives me hope it will get fixed.  Nonetheless, it is still happening in 0.64.  I propose that a good philosophy to take would be that each deviation from indent_continue=2 be separately selectable with a boolean choice.

**Comment by gmaurel** [comment]
Let us begin at new.
Please send your source, the configuration and the output files you expected to get.
The option use_indent_continue_only_once is to calculate the indentation for *ALL* the continuation line(s). Only one value will be calculated. The value depends from the option. 
FALSE: all mechanisms which produce an indentation work and the values are added. There are two:
"at the assignment" and "at the function call". The value will be twice the given value.
TRUE: only ONE of the mechanisms produces the value.

**Comment by BugZappr** [comment]
Doh!  I had deleted my old uncrustify directory, along with the config I was using; and recovered it from above.  The above file also lacks use_indent_continue_only_once!  I just now tried the stripped down cfg:

'indent_columns=4
indent_continue=2
code_width=80
cmt_width=80
indent_with_tabs=0
use_indent_continue_only_once=1'

It now IS working!  Yay!  I should have wondered why it passed your unit tests. *g*  (I wish the app I was working on could have similar ones.)  This means I can begin using this regularly, in earnest.  Many thanks, and sorry for the false alarm.  OTOH, I'm glad to have been of help to bring this capability to Uncrustify.

**Comment by BugZappr** [comment]
BTW: I've previously tried to get this to work in all the code beautifiers supported by UniversalIndentGUI, as well as clang-format.  At the time of the posting of this bug, none did; so yours is likely the only one which supports this ability.
