### ISSUE TITLE
AppVeyor badge stopped working

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#966]
It's been a couple of weeks since the last AppVeyor build succeeded on main project. Since then, all builds show up as queued or canceled.

Let's take a recent build:
https://ci.appveyor.com/project/uncrustify/uncrustify/build/547

But, apparently the builds have moved under Guy's fork instead:
https://ci.appveyor.com/project/gmaurel/uncrustify/build/312

Because of this the README badge is not working anymore.

@gmaurel How/why this happened ?

**Comment by gmaurel** [comment]
About the 17. of januar 2017 I found a problem.
There where about 6 jobs in the appVeyor with status "queued".

A search give me an answer:

http://help.appveyor.com/discussions/problems/5919-builds-are-stuck-in-queued-status

Posted by Ilya Finkelshte... on Jan 17, 2017 @ 06:21 PM:
  It should be fixed now for your account, please restart some build. Sorry for the trouble.

About 19h30 I cancelled some of the jobs and started them again.
The next day the jobs where finished.

Is it related to the problem?

**Comment by mihaipopescu** [comment]
They are not yet fixed. Take a look here https://ci.appveyor.com/project/uncrustify/uncrustify/history.

**Comment by gmaurel** [comment]
You are right.
But I don't know how to start a job again.
Can anybody help?

**Comment by mihaipopescu** [comment]
You have more settings as an administrator. Maybe if you remove the integration from your own account... I'm not sure.

I've searched online and it happened for many people. I've posted in a recent post http://help.appveyor.com/discussions/problems/3995-builds-are-queued a question. We don't know what could be the problem.

**Comment by mihaipopescu** [comment]
@gmaurel I've received word from AppVeyor and they say:
> Sorry about that. You account has been fixed. Re-start one of the queue builds or start a new one to get the queue going again.
